import { PGlite } from "@electric-sql/pglite";
import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
// Isolated database; synthetic claims check our SQL, not Google's identity service.
const db = new PGlite();
const A = "10000000-0000-4000-8000-000000000001";
const B = "10000000-0000-4000-8000-000000000002";
const ADMIN = "10000000-0000-4000-8000-000000000003";
const UNVERIFIED = "10000000-0000-4000-8000-000000000004";
const OP = "30000000-0000-4000-8000-000000000001";
let checks = 0;
const scalar = async (sql, args = []) => Object.values((await db.query(sql,args)).rows[0])[0];
async function actor(id, aal = "aal1") {
  await db.exec("reset role");
  await db.query("select set_config('request.jwt.claims',$1,false)", [JSON.stringify({sub:id,aal,user_metadata:{role:"admin"}})]);
  await db.exec(`set role ${id ? "authenticated" : "anon"}`);
}
async function denied(sql,args=[]) { await assert.rejects(db.query(sql,args)); checks++; }
await db.exec(`create role anon; create role authenticated; create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
create function auth.uid() returns uuid language sql stable as $$ select nullif(auth.jwt()->>'sub','')::uuid $$;
grant usage on schema public,auth to anon,authenticated;
grant execute on function auth.jwt(),auth.uid() to anon,authenticated;
create publication supabase_realtime;`);
const migration = await readFile(new URL("./commercial-onboarding.sql",import.meta.url),"utf8");
const enforce = await readFile(new URL("./commercial-enforce.sql",import.meta.url),"utf8");
for (const file of ["supabase.sql","finance.sql","commercial.sql"])
  await db.exec(await readFile(new URL(file,import.meta.url),"utf8"));
await db.exec(migration); await db.exec(migration);
await db.query("insert into auth.users values($1,'alpha@example.invalid',now()),($2,'beta@example.invalid',now()),($3,'owner@example.invalid',now()),($4,'unverified@example.invalid',null)",[A,B,ADMIN,UNVERIFIED]);
await db.query("insert into public.bap_admins(user_id) values($1)",[ADMIN]);
await actor(null); await denied("select public.bap_register_customer()");
await actor(UNVERIFIED); await denied("select public.bap_register_customer()");
await actor(A); await scalar("select public.bap_register_customer()");
await denied("select * from public.bap_access");
await denied("update public.bap_access set status='active'");
await denied("select public.bap_admin_list()");
await actor(null); await db.exec("reset role");
assert.equal(await scalar("select count(*) from public.bap_access"),1); checks++;
assert.equal(await scalar("select requested_plan from public.bap_access where user_id=$1",[A]),null); checks++;
const seen = await scalar("select last_seen_at::text from public.bap_access where user_id=$1",[A]);
await actor(A); await scalar("select public.bap_register_customer()");
await db.exec("reset role");
assert.equal(await scalar("select last_seen_at::text from public.bap_access where user_id=$1",[A]),seen); checks++;
assert.equal(await scalar("select count(*) from public.bap_audit where action='account_registered'"),1); checks++;
await actor(A); await scalar("select public.bap_request_access('monthly')");
await denied("select public.bap_request_access('annual')");
await denied("select public.bap_request_access('hidden')");
await actor(B); await scalar("select public.bap_register_customer()");
await actor(ADMIN); await denied("select public.bap_admin_list()");
await actor(ADMIN,"aal2");
let list = await scalar("select public.bap_admin_list()");
assert.equal(list.summary.total,2); checks++;
assert.equal(list.summary.pending,2); checks++;
assert.equal(list.customers.find(c=>c.user_id===B).requested_plan,null); checks++;
assert.equal("expenses" in list.customers[0],false); checks++;
assert.equal((await scalar("select public.bap_admin_list(0,'%')")).customers.length,0); checks++;
await denied("select public.bap_admin_list(null,'')");
await denied("select public.bap_admin_list(0,null)");
await db.exec("reset role"); await db.exec(enforce); await db.exec(enforce);
assert.equal(await scalar("select count(*) from public.bap_audit where action='enforcement'"),1); checks++;
await actor(A); assert.equal(await scalar("select public.bap_can_write()"),false); checks++;
await denied("select public.bap_admin_decide($1,$2,'active','monthly',30)",[OP,A]);
await actor(ADMIN,"aal2");
// An administrator can approve a registered customer who has not requested yet.
await scalar("select public.bap_admin_decide($1,$2,'active','monthly',30,19,'yape','SYNTHETIC-PAYMENT-001')",[OP,B]);
await db.exec("reset role");
const expiry = await scalar("select ends_at::text from public.bap_access where user_id=$1",[B]);
await actor(B); await scalar("select public.bap_register_customer()");
assert.equal(await scalar("select public.bap_can_write()"),true); checks++;
await denied("select public.bap_request_access('annual')");
await db.exec("reset role"); await db.exec(migration);
assert.equal(await scalar("select ends_at::text from public.bap_access where user_id=$1",[B]),expiry); checks++;
assert.equal(await scalar("select count(*) from public.bap_payments"),1); checks++;
await actor(ADMIN,"aal2"); list=await scalar("select public.bap_admin_list()");
assert.equal(list.summary.active,1); checks++;
assert.equal(Number(list.summary.payments_pen),19); checks++;
await db.exec("reset role");
await db.query("update public.bap_access set status='suspended',last_seen_at=now()-interval '1 hour' where user_id=$1",[B]);
await actor(B); await scalar("select public.bap_register_customer()");
let mine=await scalar("select public.bap_my_access()");
assert.equal(mine.status,"suspended"); checks++;
assert.equal(mine.can_write,false); checks++;
assert.equal(mine.payments.length,1); checks++;
await denied("select public.bap_request_access('monthly')");
await db.exec("reset role");
assert.equal(await scalar("select last_seen_at>now()-interval '5 minutes' from public.bap_access where user_id=$1",[B]),true); checks++;
await db.close();
console.log(`Commercial onboarding: ${checks} checks passed (isolated PostgreSQL).`);
