'use strict';
(function(){
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v)||0),num=v=>Number(v)||0;
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const M=window.BAP_FINANCE_MODEL;let db,records=[],connected=null,channel=null,busy=false,status='Cargando…',edit=null,context=null,formKind=null;
const state=()=>window.BAP_APP?.state()||{user:null,configured:false,expenses:[],cloud:null};
const owner=()=>state().user?.id||null;
const visible=()=>records.filter(r=>r.owner_id===owner()&&(!state().configured||!!owner()));
const active=()=>visible().filter(r=>!r.deleted);
function transact(mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction('records',mode);const req=action(tx.objectStore('records'));tx.oncomplete=()=>resolve(req?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
const load=()=>transact('readonly',s=>s.getAll());const put=r=>transact('readwrite',s=>s.put(r));
const notify=s=>window.BAP_APP?.notice(s);
function allowed(){if(state().configured&&!owner()){q('#account-dialog').showModal();notify('Inicia sesión para registrar tus finanzas.');return false}return !!db}
async function save(kind,data,id){if(!allowed())return;const account=owner();const r={id:id||crypto.randomUUID(),kind,data,owner_id:account,updated_at:new Date().toISOString(),deleted:false,dirty:true};if(!M.validRecord(r))throw Error('Registro inválido');await put(r);records=await load();if(owner()===account)render();sync();return r}
function chooseCredit(){const el=q('#expense-credit');if(!el)return;const selected=el.value;el.innerHTML='<option value="">Efectivo / débito / transferencia</option>'+active().filter(r=>r.kind==='debt'&&r.data.type==='card').map(d=>`<option value="${esc(d.id)}">Crédito · ${esc(d.data.name)}</option>`).join('');if([...el.options].some(o=>o.value===selected))el.value=selected}
async function attach(){if(!db)return;const s=state(),id=s.user?.id||null;if(connected!==id){if(channel&&s.cloud)s.cloud.removeChannel(channel);channel=null;connected=id;records=await load();if(id&&s.cloud){channel=s.cloud.channel('bap-finance-'+id).on('postgres_changes',{event:'*',schema:'public',table:'finance_entries',filter:'user_id=eq.'+id},()=>sync()).subscribe();sync()}else status=s.configured?'Inicia sesión para sincronizar':'Solo en este dispositivo'}else if(!id&&!busy){status=s.configured?'Inicia sesión para sincronizar':'Solo en este dispositivo'}render()}
async function sync(){const s=state();if(!db||!s.cloud||!s.user||busy||!navigator.onLine)return;const id=s.user.id;busy=true;status='Sincronizando finanzas…';paintStatus();try{for(const r of records.filter(r=>r.owner_id===id&&r.dirty)){if(owner()!==id)return;let {data:remote,error}=await s.cloud.from('finance_entries').select('updated_at').eq('id',r.id).maybeSingle();if(error)throw error;if(remote&&Date.parse(remote.updated_at)>Date.parse(r.updated_at))continue;let row={id:r.id,user_id:id,kind:r.kind,data:r.data,updated_at:r.updated_at,deleted:r.deleted};let result=await s.cloud.from('finance_entries').upsert(row,{onConflict:'id'});if(result.error)throw result.error;const latest=records.find(x=>x.id===r.id);if(latest?.updated_at===r.updated_at){latest.dirty=false;await put(latest)}}let offset=0,downloaded=[];while(true){let {data,error}=await s.cloud.from('finance_entries').select('*').order('id').range(offset,offset+499);if(error)throw error;downloaded.push(...data);if(data.length<500)break;offset+=500}if(owner()!==id)return;for(const r of downloaded){const local=records.find(x=>x.id===r.id);if(!local||!local.dirty||Date.parse(r.updated_at)>Date.parse(local.updated_at))await put({id:r.id,owner_id:r.user_id,kind:r.kind,data:r.data,updated_at:r.updated_at,deleted:r.deleted,dirty:false})}records=await load();status=records.some(r=>r.owner_id===id&&r.dirty)?'Cambios pendientes':'Finanzas sincronizadas';render()}catch(e){console.error('Finance sync',e);status=['42P01','PGRST205'].includes(e.code)?'Datos locales · falta activar finanzas en la nube':'Sincronización pendiente · datos guardados aquí';paintStatus()}finally{busy=false}}
function paintStatus(){const el=q('#finance-sync');el.textContent=status;el.classList.toggle('pending',status.includes('pendiente')||status.includes('locales')||status.includes('dispositivo'))}
const metric=(name,value,caption,cls='')=>`<div class="finance-metric ${cls}"><span>${esc(name)}</span><strong>${fmt(value)}</strong><small>${esc(caption)}</small></div>`;
const row=(name,value)=>`<div class="finance-row"><span>${esc(name)}</span><strong>${fmt(value)}</strong></div>`;
function render(){if(!db)return;paintStatus();chooseCredit();const period=q('#month').value||day().slice(0,7),rs=visible(),s=state(),a=M.analyze(rs,s.expenses,period,day());
q('#finance-summary').innerHTML=metric('Ingresos cobrados',a.earned,'Incluye intereses cobrados con desglose','good')+metric('Gastos de consumo',a.purchases,'Incluye compras a crédito')+metric('Deuda actual',a.totalDebt,'Saldo según registros, a la fecha','debt')+metric('Flujo neto del mes',a.cashFlow,'No equivale a saldo bancario');
const bars=[{v:a.cashBudget,c:'#9ab6be'},{v:a.payments+a.pending,c:'#7190b9'},{v:a.reserve,c:'#a7c88c'},{v:a.extra,c:'#dfb481'},{v:a.savings,c:'#ae9bc4'}],base=bars.reduce((n,x)=>n+x.v,0);
q('#finance-plan').innerHTML=`<p class="finance-help">${a.settings.income==null?'Usa ingresos efectivamente cobrados del mes.':'Escenario con ingreso mensual esperado: '+fmt(a.incomeBase)+'. No garantiza que ya esté disponible.'} Presupuesto de efectivo/débito separado de pagos de deuda.</p>`+row('Ingreso usado para el plan',a.incomeBase)+row('Gastos efectivo/débito: registrado o presupuesto mayor',a.cashBudget)+row('Pagos de deuda ya registrados',a.payments)+row('Cuotas o mínimos pendientes del mes',a.pending)+(a.lent?row('Dinero prestado durante el mes',a.lent):'')+row('Reserva para imprevistos',a.reserve)+row('Abono adicional propuesto',a.extra)+row('Ahorro / metas disponible',a.savings)+`<div class="allocation-track" aria-hidden="true">${bars.map(b=>`<i style="width:${base?b.v/base*100:0}%;background:${b.c}"></i>`).join('')}</div><div class="plan-remainder"><span>${a.deficit?'DÉFICIT DEL PRESUPUESTO':a.planReady?'EXCEDENTE DESPUÉS DE OBLIGACIONES Y RESERVA':'DATOS PENDIENTES PARA DISTRIBUIR'}</span><strong>${a.deficit?fmt(a.deficit):a.planReady?fmt(a.surplus):'Completa los datos del plan'}</strong></div>`;
let advice=a.warnings.map(t=>`<div class="finance-advice-item warning">${esc(t)}</div>`).join('');
if(a.allocations.length)advice+=`<div class="finance-advice-item"><strong>${a.settings.strategy==='snowball'?'Bola de nieve · menor saldo primero':'Avalancha · mayor TEA conocida primero'}</strong>${a.allocations.map(x=>`${esc(x.name)}: abono adicional ${fmt(x.extra)}`).join('<br>')}<br>Confirma con la entidad la aplicación al capital y sus condiciones. Este orden no compara comisiones ni condiciones especiales.</div>`;
const reserveTarget=Math.max(0,num(a.settings.targetMonths??3))*Math.max(0,num(a.settings.expenses)),reserveHave=num(a.settings.emergency);
if(reserveTarget>reserveHave)advice+=`<div class="finance-advice-item"><strong>Construye tu reserva</strong>Meta configurable: ${fmt(reserveTarget)} (${num(a.settings.targetMonths??3)} meses de gastos presupuestados). Saldo que registraste: ${fmt(reserveHave)}. Faltan ${fmt(reserveTarget-reserveHave)}. La reserva propuesta no se suma al ahorro hasta que tú la registres.</div>`;
if(!a.deficit&&a.planReady&&a.savings>0)advice+=`<div class="finance-advice-item"><strong>Distribuye según tus prioridades</strong>${a.totalDebt>0?'Mantén el ahorro para imprevistos y metas cercanas; compara el costo de la deuda antes de asumir riesgo de inversión.':reserveHave<reserveTarget?'Prioriza completar tu reserva antes de invertir dinero que puedes necesitar pronto.':'Separa metas de corto plazo y ahorro de largo plazo. Antes de elegir inversiones, define plazo, tolerancia a pérdidas y necesidad de liquidez; este panel no recomienda productos específicos.'}</div>`;
const first=a.ordered[0];if(first&&!a.missingRates&&a.planReady){const proj=M.project(first,a.allocations.find(x=>x.id===first.id)?.extra||0);advice+=`<div class="finance-advice-item"><strong>Simulación de ${esc(first.data.name)}</strong>${proj.status==='estimated'?`Aproximadamente ${proj.months} meses e intereses ${fmt(proj.interest)} si mantienes una cuota fija, la TEA registrada y el abono extra cada mes, sin nuevas compras ni comisiones. No es un cronograma bancario.`:proj.status==='insufficient'?'El pago propuesto no cubre el interés estimado; revisa cuota y tasa con la entidad.':'Completa la TEA y cuota para obtener una simulación. Horizonte máximo: 50 años.'}</div>`}
q('#finance-advice').innerHTML=advice||'<div class="finance-empty">Registra tus ingresos, presupuesto y obligaciones para construir tu plan.</div>';
q('#finance-cash').innerHTML=row('Ingresos cobrados (sin repetir intereses de cobros)',a.directEarned)+row('Préstamos recibidos: financiación',a.borrowed)+row('Cobros de dinero prestado',a.recovered)+row('Gastos por efectivo/débito',a.cashExpenses)+row('Pagos de tarjetas y préstamos',a.payments)+row('Dinero que prestaste',a.lent)+row('Flujo neto de los movimientos registrados',a.cashFlow);
q('#finance-incomes').innerHTML=events(rs.filter(r=>!r.deleted&&r.kind==='income'&&r.data.date?.slice(0,7)===period));
q('#finance-debts').innerHTML=a.debts.map(d=>debtCard(d,false)).join('')||'<div class="finance-empty">Agrega tu primera tarjeta o préstamo recibido.</div>';
q('#finance-receivables').innerHTML=a.receivables.map(d=>debtCard(d,true)).join('')||'<div class="finance-empty">Registra el dinero que otras personas te deben.</div>';
const eventRows=rs.filter(r=>!r.deleted&&['payment','disbursement','charge'].includes(r.kind)&&r.data.date?.slice(0,7)===period);
q('#finance-debt-events').innerHTML=events(eventRows.filter(r=>a.debts.some(d=>d.id===r.data.debt_id)));q('#finance-loan-events').innerHTML=events(eventRows.filter(r=>a.receivables.some(d=>d.id===r.data.debt_id)));
}
function debtCard(d,isLoan){const x=d.data,b=d.balance;return `<article class="debt-card"><header><div><span class="eyebrow">${isLoan?'POR COBRAR':x.type==='card'?'TARJETA DE CRÉDITO':'PRÉSTAMO / DEUDA'}</span><h3>${esc(x.name)}</h3></div><span class="badge ${d.overdue?'late':''}">${b===0?'Sin saldo':d.overdue?'Revisar atraso':'Activo'}</span></header><div class="balance">${fmt(b)}</div><small class="finance-help">Saldo actual según tu registro · S/</small><dl><div><dt>${isLoan?'Fecha acordada':'Próximo vencimiento'}</dt><dd>${esc(x.due||'Sin registrar')}</dd></div><div><dt>${isLoan?'Cuota esperada':'Cuota / mínimo mensual'}</dt><dd>${x.minimum==null?'Sin registrar':fmt(x.minimum)}</dd></div><div><dt>TEA registrada</dt><dd>${x.tea==null?'Desconocida':esc(x.tea)+'%'}</dd></div><div><dt>${x.type==='card'?'Línea disponible según saldo':'Saldo base'}</dt><dd>${x.type==='card'?(x.limit?fmt(Math.max(0,x.limit-b)):'Sin límite registrado'):fmt(x.balance)}</dd></div>${x.type==='card'?`<div><dt>Día de corte</dt><dd>${esc(x.cut||'Sin registrar')}</dd></div>`:''}</dl><div class="debt-actions"><button class="primary" data-fin-action="payment" data-id="${esc(d.id)}">${isLoan?'Registrar cobro':'Registrar pago'}</button><button class="outline" data-fin-action="disbursement" data-id="${esc(d.id)}">${isLoan?'Prestar más':'Desembolso recibido'}</button>${isLoan?'':`<button class="outline" data-fin-action="charge" data-id="${esc(d.id)}">Interés / cargo</button>`}<button class="text-btn" data-fin-edit="${esc(d.id)}">Editar</button><button class="text-btn" data-fin-delete="${esc(d.id)}">Eliminar</button></div></article>`}
function events(rows){return rows.sort((a,b)=>(b.data.date||'').localeCompare(a.data.date||'')).map(r=>{let debt=active().find(x=>x.id===r.data.debt_id);let label=r.kind==='income'?r.data.name:r.kind==='payment'?(debt?.kind==='receivable'?'Cobro':'Pago'):r.kind==='disbursement'?(debt?.kind==='receivable'?'Dinero prestado':'Préstamo recibido'):'Cargo a deuda';return `<div class="finance-event"><div><strong>${esc(label)}${debt?' · '+esc(debt.data.name):''}</strong><small>${esc(r.data.date)}${r.data.source?' · '+esc(r.data.source):''}${r.kind==='payment'?' · Capital: '+(r.data.principal==null?'pendiente':fmt(r.data.principal)):''}${r.data.note?' · '+esc(r.data.note):''}</small></div><span>${fmt(r.data.amount)}</span><button class="text-btn" data-fin-edit="${esc(r.id)}">Editar</button><button class="delete" data-fin-delete="${esc(r.id)}" aria-label="Eliminar registro financiero">×</button></div>`}).join('')||'<div class="finance-empty">Sin movimientos en el período seleccionado.</div>'}
const field=(id,label,type='text',value='',opts='')=>`<label>${esc(label)}<input id="f-${id}" name="${id}" type="${type}" value="${esc(value??'')}" ${opts}></label>`;
const select=(id,label,values,value)=>`<label>${esc(label)}<select id="f-${id}" name="${id}">${values.map(([v,t])=>`<option value="${esc(v)}"${String(value)===String(v)?' selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function open(kind,id=null,debtId=null){if(!allowed())return;edit=id?active().find(r=>r.id===id):null;context=debtId||edit?.data.debt_id;formKind=kind;const d=edit?.data||{},moneyOpts='min="0" max="999999999" step="0.01"',required=moneyOpts+' required';let fields='',help='',title='';
if(kind==='income'){title='Registrar ingreso cobrado';fields=field('name','Descripción / fuente','text',d.name,'required maxlength="100"')+field('amount','Monto recibido (S/)','number',d.amount,required.replace('min="0"','min="0.01"'))+field('date','Fecha de cobro','date',d.date||day(),'required max="'+day()+'"')+select('source','Tipo de ingreso',[['Sueldo','Sueldo'],['Servicios','Servicios / BAP'],['Ventas','Ventas'],['Otros','Otros']],d.source||'Sueldo');help='Solo dinero ganado y recibido. Los préstamos y devoluciones de capital se registran por separado.'}
if(['debt','receivable'].includes(kind)){title=kind==='debt'?'Tarjeta o deuda':'Dinero por cobrar';fields=field('name','Alias / entidad o persona','text',d.name,'required maxlength="100"')+(kind==='debt'?select('type','Tipo',[['card','Tarjeta de crédito'],['loan','Préstamo recibido'],['other','Otra deuda']],d.type||'card'):'')+field('balance','Saldo base pendiente (S/)','number',d.balance??0,required)+field('date','Fecha base del saldo','date',d.date||day(),'required max="'+day()+'"')+field('minimum',kind==='debt'?'Cuota / mínimo mensual (S/), vacío si desconocido':'Cuota acordada (S/), opcional','number',d.minimum,moneyOpts)+field('due','Próximo vencimiento, opcional','date',d.due)+field('tea','TEA % (0 si sin interés; vacío si desconocida)','number',d.tea,'min="0" max="2000" step="0.01"')+(kind==='debt'?field('limit','Límite tarjeta (S/), opcional','number',d.limit,moneyOpts)+field('cut','Día de corte tarjeta, opcional','number',d.cut,'min="1" max="31" step="1"'):'');help='El saldo base no genera un ingreso ni una salida de efectivo. Debe ser anterior a los movimientos del día base: la app suma compras/cargos/desembolsos y resta capital desde esa fecha, inclusive. Para conciliar, usa un saldo y fecha que no dupliquen movimientos. La TEA debe venir del contrato, no sustituirla por TCEA.'}
if(['payment','disbursement','charge'].includes(kind)){const debt=active().find(r=>r.id===context);if(!debt)return;title=kind==='payment'?(debt.kind==='receivable'?'Registrar cobro':'Registrar pago'):kind==='disbursement'?(debt.kind==='receivable'?'Registrar dinero prestado':'Registrar desembolso recibido'):'Interés o cargo a la deuda';fields=field('amount',kind==='charge'?'Cargo que aumenta la deuda (S/)':'Importe total (S/)','number',d.amount,required.replace('min="0"','min="0.01"'))+(kind==='payment'?field('principal','Parte aplicada a capital (S/), vacío si desconocida','number',d.principal,moneyOpts):'')+field('date','Fecha del movimiento','date',d.date||day(),'required max="'+day()+'" min="'+esc(debt.data.date)+'"');help=kind==='payment'?'El capital reduce el saldo. La diferencia entre total y capital representa intereses/cargos; consulta el comprobante. Si dejas capital vacío, se registra el efectivo sin reducir todavía la deuda. Actualiza el próximo vencimiento y mínimo desde Editar después de cada ciclo.':kind==='charge'?'Aumenta el saldo sin movimiento de efectivo; no vuelvas a sumarlo si ya está incluido en el saldo base.':'Aumenta el saldo y registra la entrada (préstamo recibido) o salida (dinero prestado) de efectivo. No lo registres también como ingreso o gasto.'}
if(kind==='settings'){title='Tu presupuesto y estrategia';fields=field('income','Ingreso mensual esperado (S/), vacío = cobrado','number',d.income,moneyOpts)+field('expenses','Presupuesto efectivo/débito del mes (S/)','number',d.expenses??0,required)+field('reserve','Aporte mensual para imprevistos (S/)','number',d.reserve??0,required)+field('emergency','Fondo de emergencia que ya tienes (S/)','number',d.emergency??0,required)+field('targetMonths','Meta de reserva: meses de gastos','number',d.targetMonths??3,'min="0" max="24" step="1" required')+field('debtPercent','% del excedente para abonos extra','number',d.debtPercent??80,'min="0" max="100" step="1" required')+select('strategy','Orden de abonos',[['avalanche','Avalancha: mayor TEA conocida'],['snowball','Bola de nieve: menor saldo']],d.strategy||'avalanche');help='El ingreso esperado es un escenario, no efectivo disponible. Presupuesta gastos de efectivo/débito sin incluir pagos de deuda ni compras a crédito. Si tus gastos registrados son mayores, se utiliza el mayor valor. Primero se cubren cuotas pendientes y reserva; el porcentaje se aplica al excedente. Las metas de reserva y porcentajes son editables.'}
if(kind!=='settings')fields+=field('note','Nota, opcional','text',d.note,'maxlength="200"');q('#finance-title').textContent=title;q('#finance-fields').innerHTML=fields;q('#finance-form-help').textContent=help;q('#finance-error').textContent='';q('#finance-editor').showModal();}
q('#finance-form').onsubmit=async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));const numeric=['amount','principal','balance','minimum','tea','limit','cut','income','expenses','reserve','emergency','targetMonths','debtPercent'];for(const k of numeric)if(k in data)data[k]=data[k]===''?null:Number(data[k]);if(context)data.debt_id=context;const err=q('#finance-error');err.textContent='';if(data.principal!=null&&(data.principal<0||data.principal>data.amount))return err.textContent='El capital debe estar entre cero y el importe total.';const debt=active().find(r=>r.id===context);if(formKind==='payment'&&debt){let rows=visible().filter(r=>r.id!==edit?.id),b=M.balance(debt,rows,state().expenses);if(data.principal>b+.005)return err.textContent='El capital supera el saldo registrado. Revisa el saldo y movimientos.'}if(data.name)data.name=data.name.trim();if(['income','debt','receivable'].includes(formKind)&&!data.name)return err.textContent='Escribe un nombre o alias.';q('#finance-save').disabled=true;try{const id=formKind==='settings'?(edit?.id||owner()||'00000000-0000-4000-8000-000000000001'):edit?.id;await save(formKind,data,id);q('#finance-editor').close();notify('Registro financiero guardado.')}catch(e){err.textContent='No se pudo guardar; revisa el almacenamiento del navegador.';console.error(e)}finally{q('#finance-save').disabled=false}};
q('#finance-close').onclick=q('#finance-cancel').onclick=()=>q('#finance-editor').close();q('#finance-settings').onclick=()=>{const r=active().find(r=>r.kind==='settings');open('settings',r?.id)};
q('#finanzas').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.finTab){document.querySelectorAll('[data-fin-tab]').forEach(el=>el.setAttribute('aria-selected',String(el===b)));document.querySelectorAll('[data-fin-panel]').forEach(el=>el.hidden=el.dataset.finPanel!==b.dataset.finTab)}if(b.dataset.finAdd)open(b.dataset.finAdd);if(b.dataset.finAction)open(b.dataset.finAction,null,b.dataset.id);if(b.dataset.finEdit){const r=active().find(r=>r.id===b.dataset.finEdit);if(r)open(r.kind,r.id)}if(b.dataset.finDelete){const r=active().find(r=>r.id===b.dataset.finDelete);if(!r)return;if(['debt','receivable'].includes(r.kind)&&(active().some(x=>x.data.debt_id===r.id)||state().expenses.some(x=>!x.deleted&&x.credit_id===r.id)))return notify('Elimina primero los movimientos vinculados o conserva la cuenta con saldo cero.');if(!confirm('¿Eliminar este registro financiero? Se sincronizará la eliminación en tus dispositivos.'))return;await put({...r,deleted:true,dirty:true,updated_at:new Date().toISOString()});records=await load();render();sync()}};
q('#month').addEventListener('change',render);window.addEventListener('bap:render',attach);window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
q('#finance-backup').onclick=()=>{if(!allowed())return;download(new Blob([JSON.stringify({format:'bap-finance-v1',exported:new Date().toISOString(),records:visible()},null,2)],{type:'application/json'}),'BAP_Finanzas_'+day()+'.json')};
q('#finance-restore').onchange=async e=>{const file=e.target.files[0];if(!file||!allowed())return;try{const backup=JSON.parse(await file.text());if(backup.format!=='bap-finance-v1'||!Array.isArray(backup.records)||backup.records.length>50000)throw Error('Formato');for(const r of backup.records)if(!M.validRecord(r))throw Error('Registro');const allIds=new Set([...active().filter(r=>['debt','receivable'].includes(r.kind)),...backup.records.filter(r=>!r.deleted&&['debt','receivable'].includes(r.kind))].map(r=>r.id));for(const r of backup.records)if(!r.deleted&&['payment','disbursement','charge'].includes(r.kind)&&!allIds.has(r.data.debt_id))throw Error('Cuenta vinculada ausente');if(!confirm('¿Restaurar estos registros financieros en la cuenta actual? Los ID coincidentes se reemplazarán.'))return;await transact('readwrite',store=>{for(const r of backup.records){const id=r.kind==='settings'?(owner()||'00000000-0000-4000-8000-000000000001'):r.id;store.put({...r,id,owner_id:owner(),updated_at:new Date().toISOString(),deleted:!!r.deleted,dirty:true})}});records=await load();render();sync();notify('Respaldo financiero restaurado.')}catch(err){notify('El archivo no es un respaldo financiero válido.')}finally{e.target.value=''}};
function reportRows(){const period=q('#month').value;return active().filter(r=>r.kind!=='settings'&&(['debt','receivable'].includes(r.kind)||r.data.date?.slice(0,7)===period)).map(r=>[r.data.date,r.kind,r.data.name||active().find(d=>d.id===r.data.debt_id)?.data.name||'',r.data.amount??r.data.balance??0,r.data.principal??'',r.data.minimum??'',r.data.tea??'',r.data.due||'',r.data.note||''])}
q('#finance-excel').onclick=()=>{if(!allowed())return;const rows=reportRows();if(!rows.length)return notify('No hay registros financieros para exportar.');download(window.BAP_XLSX.createTable(['Fecha','Tipo','Descripción / cuenta','Monto o saldo base S/','Capital S/','Cuota S/','TEA %','Vencimiento','Nota'],rows,[3,4,5,6],'Finanzas',[3,4,5]),`BAP_Finanzas_${q('#month').value}.xlsx`)};
q('#finance-pdf').onclick=()=>{if(!allowed())return;const a=M.analyze(visible(),state().expenses,q('#month').value,day()),w=window.open('','_blank');if(!w)return notify('Permite ventanas emergentes para exportar PDF.');w.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>BAP · Plan financiero</title><style>body{font:13px/1.6 Arial;color:#172b47;margin:35px}h1{font-size:27px}h2{margin-top:26px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid #dce5ec}th{background:#edf3f5}.finance-row{display:flex;justify-content:space-between;padding:9px;border-bottom:1px solid #eee}.allocation-track{display:none}.plan-remainder{padding:15px;background:#edf3f5}p{color:#5c7185}.finance-advice-item{margin:10px 0;padding:10px;background:#f5f7fa}button{display:none}@page{size:A4;margin:18mm}</style></head><body><h1>BAP · Plan financiero</h1><p>Período ${esc(q('#month').value)} · Emitido ${esc(day())} · Saldos actuales según registro</p><h2>Distribución propuesta</h2>${q('#finance-plan').innerHTML}<h2>Guía y supuestos</h2>${q('#finance-advice').innerHTML}<h2>Deudas</h2><table><thead><tr><th>Cuenta</th><th>Saldo</th><th>Cuota registrada</th><th>Vence</th></tr></thead><tbody>${a.debts.map(d=>`<tr><td>${esc(d.data.name)}</td><td>${fmt(d.balance)}</td><td>${d.data.minimum==null?'Desconocida':fmt(d.data.minimum)}</td><td>${esc(d.data.due||'Pendiente')}</td></tr>`).join('')}</tbody></table><p>Orientación automática. La simulación excluye nuevas compras, comisiones y cambios de tasa. No constituye un cronograma bancario.</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
window.BAP_FINANCE={cards:()=>active().filter(r=>r.kind==='debt'&&r.data.type==='card'),async clearOwner(id){for(const r of records.filter(r=>r.owner_id===id))await transact('readwrite',s=>s.delete(r.id));records=await load();render()}};
const request=indexedDB.open(state().demo?'bap-finance-demo-v1':'bap-finance-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('records',{keyPath:'id'});request.onsuccess=async()=>{db=request.result;records=await load();if(state().demo){const banner=document.createElement('div');banner.className='finance-advice-item warning';banner.innerHTML='<strong>Demostración con datos ficticios</strong>Este espacio usa una base separada y no sincroniza con tu cuenta. <a href="./">Volver a mis finanzas</a>';q('main').prepend(banner);if(!records.length){const first=day().slice(0,7)+'-01',cardId=crypto.randomUUID(),sample=[{id:cardId,kind:'debt',data:{name:'Tarjeta de ejemplo',type:'card',balance:2400,date:first,minimum:180,tea:45,limit:5000,due:day().slice(0,7)+'-20',cut:5}},{id:crypto.randomUUID(),kind:'income',data:{name:'Sueldo de ejemplo',amount:3500,date:first,source:'Sueldo'}},{id:'00000000-0000-4000-8000-000000000001',kind:'settings',data:{expenses:1800,reserve:200,emergency:600,targetMonths:3,debtPercent:80,strategy:'avalanche'}}];for(const r of sample)await put({...r,owner_id:null,updated_at:new Date().toISOString(),deleted:false,dirty:false});records=await load()}}status=state().configured?'Inicia sesión para sincronizar':'Solo en este dispositivo';await attach();setInterval(sync,30000)};request.onerror=()=>{status='No se pudo abrir la base financiera';paintStatus()};
})();
